#!/bin/bash
AEASRC=git@bitbucket.org:aeaverification
AEAHSRC=bitbucket.org/aeaverification
call=$0
os=$(uname)
codeeditor="$(which code)"

function code {
    case $os in
	    Linux|Darwin)
		    "$codeeditor" "$1"
		    ;;
	    *)
		    echo "Open $1 with editor of your choice"
		    ;;

    esac
    }

if [[ -z $1 ]]
then
  cat << EOF
  $0 (number)

  will check out the repo from the AEA repository at
    $AEASRC
  into the local directory, enter the directory, and open 
  an editor with the REPLICATION.md file.
EOF
else
manuscript=$1
repo=aearep-$manuscript

case $2 in
    s*|S*)
       method=ssh
       ;;
    h*|H*)
       method=https
       ;;
    *)
       method=ssh
       ;;
esac

# construct URL and query other parameters if necessary

case $method in
  ssh)
    GITURL="$AEASRC/$repo.git"
    ;;
  https)
    # we need username and PAT
    echo "We will use pre-configured credentials for git."
    echo "If this does not work, run 'git config --global credential.helper store' "
    echo "and try again."
    echo " --- "
    GITURL="https://$AEAHSRC/$repo.git"
    ;;
esac

if [[ -d $repo ]]
then 
  echo "Repo $repo already exists - updating only"
else
  git clone $GITURL
fi

# directory should exist now
if [[ -d $repo ]]
then
  cd $repo && git pull
  [[ -f REPLICATION.md && "$os" == "Linux" ]] && code . REPLICATION.md
  [[ -f REPLICATION.md && "$os" == "Darwin" ]] && open -a "Visual Studio Code" . REPLICATION.md
else
  echo "Git clone failed"
fi

echo "Done"
echo "Type cd $repo"
case $os in
	Linux)
  [[ -z $(which xclip) ]] || echo "cd $repo" | xclip -selection c
;;
   Darwin)
     echo "cd $repo" | pbcopy
     ;;
esac
fi
