#!/bin/bash
os=$(uname)
apperror=0
#set -e
CSSURL=https://gist.githubusercontent.com/dashed/6714393/raw/ae966d9d0806eb1e24462d88082a0264438adc50/github-pandoc.css
CSSLOCAL=.local.css
WKHTMLOPTS="-V margin-top=1in -V margin-left=1in -V margin-right=1in -V margin-bottom=1in"
ICPSRMSG="Details in the full report, which you will receive via ScholarOne shortly. Please provide your response to the items listed above via the openICPSR Project Communication log, specifying AEAREP-xxx. Other items in the report may need to be addressed via ScholarOne."

# print help

cat << EOF

$0 (name of extra file)

This script will take 'REPLICATION.md', transform it into a PDF,
save it as REPLICATION.raw.pdf, then merge it with the second
argument to create REPLICATION.pdf. 

You will need to then run 'aeaready' with the 'nopdf' option.

EOF


exit_on_error() {
    exit_code=$1
    exit_message=${@:2}
    if [ $exit_code -ne 0 ]; then
        >&2 echo "${exit_message}, exit code ${exit_code}."
        exit $exit_code
    fi
}


# rest of the stuff
case $os in
   Linux)
      echo "OK"
      ;;
   *)
      echo "This script only works on Linux"
      ;;
esac
nopdf=0
if [[ "$1" == "nopdf" ]]
then
   nopdf=1
   shift
fi

extrafile="$1"

if [[ ! -f "$extrafile" ]]
then
   #echo "Need a second argument that is a file"
   exit_on_error 2 "Need a second argument that is a file"
fi


set -o history -o histexpand


case $os in
	    Linux)
		    pandoc=$(which pandoc)
            [[ -f $pandoc ]] || apperror=1
            wkhtmltopdf=$(which wkhtmltopdf)
            [[ -f $wkhtmltopdf ]] || apperror=1
	       pdfengine="--pdf-engine wkhtmltopdf"
	       export QT_STYLE_OVERRIDE=fusion 
	    # get the CSS
	    curl $CSSURL > $CSSLOCAL && PANDOCXTRA="$WKHTMLOPTS -c $CSSLOCAL"
          qpdf=$(which qpdf)
          [[ -f $qpdf ]] || apperror=1
		    ;;
            Darwin)
            # for MacOS, might want to install Rstudio (comes with pandoc) and replace the line above with the outcome of
            #   find /Applications -name pandoc -type f
            pandoc=/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc
            # later versions have it bundled in the quarto directory
            [[ ! -f $pandoc ]] && pandoc=/Applications/RStudio.app/Contents/MacOS/quarto/bin/pandoc
            [[ ! -f $pandoc ]] && pandoc=/Applications/RStudio.app/Contents/MacOS/quarto/bin/tools/pandoc
            # let's see if its there
            if [[ ! -f $pandoc ]]
            then
              echo "We suggest using pandoc from the RStudio install. Searching for a different one..."
              pandoc=$(find /Applications -name pandoc -type f)
            fi
            echo "Found pandoc at $pandoc"
	    # get the CSS
	    curl $CSSURL > $CSSLOCAL && PANDOCXTRA="$WKHTMLOPTS -c $CSSLOCAL"
            ;;
	    *)
		    echo "Please review the script to define your OS"
            apperror=1
		    ;;
esac


# other stuff 

if [[ "$apperror" == "1" ]]
then
    echo "We need pandoc, wkhtmltopdf, qpdf"
    echo "One or the other not found"
    case $os in
        Darwin)
            echo "Install Rstudio to get pandoc"
            echo "Try: brew cask install wkhtmltopdf"
            ;;
        *)
            echo "Please install"
            ;;
    esac
    exit_on_error 2 pandoc  wkhtmltopdf or qpdf missing
fi 



# update the CSS

if [[ -f $CSSLOCAL ]]
then
   echo 'pre, code { white-space: pre-wrap !important; } ' >> $CSSLOCAL
fi

## Test if we are where we think we should be

if [[ ! -d ".git" ]]
then 
   exit_on_error 2 Not in right directory
fi

if [[ ! -f "REPLICATION.md" ]]
then
   exit_on_error 2 Missing REPLICATION.md -required-
fi

# convert to PDF, just in case
# requires: wkhtmltopdf and pandoc

if [[ "$nopdf" == "0" ]]
then
   $pandoc $pdfengine REPLICATION.md -f gfm -t html5 -o REPLICATION.raw.pdf --metadata pagetitle="Report for AEAREP-$num" $PANDOCXTRA
else
  echo "Skipping PDF generation as requested"
fi

rm $CSSLOCAL

# Merge files
qpdf --empty --pages "REPLICATION.raw.pdf" "$extrafile" -- "REPLICATION.pdf"
[[ -f REPLICATION.pdf ]]  || exit_on_error 2 Missing PDF -something went wrong-

echo "-------- Current git status -----------"
git status

