#!/bin/bash


#if [[ "$1" == "sug" ]]
#then
#	sed -i.bak2 '/-------/r'<(grep SUGGESTED REPLICATION.md | sed 's/>/-/') REPLICATION.md
#fi
sed -i.bak '/-----action items go here------/r'<(grep -E "REQUIRED|SUGGESTED" REPLICATION.md | sed 's/>/-/') REPLICATION.md

