#!/bin/bash

REPOLOC=git@github.com:AEADataEditor/editor-scripts.git
BASHRC=$HOME/.bashrc
ALT=$HOME/.profile
echo "This will clone the AEA repo, and add it to your PATH"
echo " - Repo: $REPOLOC"
if [[ -f $BASHRC ]] 
then
	echo " - Adding to $BASHRC"
elif [[ -f $ALT ]]
then
	echo " - Adding to $ALT"
	BASHRC=$ALT
else
	echo " Did not find $BASHRC or $ALT - not adding"
fi

echo "Hit enter to continue"
read



# clone
[[ -d $HOME/bin ]] || mkdir $HOME/bin
cd $HOME/bin
git clone $REPOLOC aea-scripts

# adding to PATH
echo "# Added by aeascripts / Lars Vilhuber $(date)
export PATH=$HOME/bin/aeascripts:$PATH
" >> $BASHRC

echo "Done"

