#!/bin/bash

SOFTWARE=stata
VERSION=17
TAG=2024-02-13
MYHUBID=dataeditors
MYNAME=${SOFTWARE}${VERSION}
MYIMG=$MYHUBID/${MYNAME}:${TAG}
[[ -z $STATALIC ]] && STATALIC=$(find $HOME/Dropbox/ -name stata.lic.??| sort | tail -1)
[[ -z $STATALIC ]] && STATALIC=$(find $(pwd)/ -name stata.lic* | sort | tail -1)
[[ -z $STATALIC ]] && STATALIC=$(find $HOME/ -name stata.lic* | sort | tail -1)

if [[ -z $STATALIC ]]
then
	echo "Could not find Stata license"
	grep STATALIC $0
	exit 2
fi

dockerbin=$(which docker1 2>/dev/null)
[[ -z $dockerbin ]] && dockerbin=$(which docker)
[[ -z $dockerbin ]] && exit 2

$dockerbin run -it --rm \
  -v "${STATALIC}":/usr/local/stata/stata.lic \
  -v "$(pwd)":/project \
  -w /project \
  --entrypoint /bin/bash \
  $MYIMG $@

date
echo "Exit: $(date +%F)"
system-info.sh
echo ""
printf "%s " "*" $(docker --version)
echo ""
printf "* %s version %d (Docker image %s)" $SOFTWARE $VERSION $MYIMG
echo ""



