#!/bin/bash

SOFTWARE=stata
VERSION=17
TAG=2022-01-17
MYHUBID=dataeditors
MYNAME=${SOFTWARE}${VERSION}
MYIMG=$MYHUBID/${MYNAME}:${TAG}
STATALIC=$(find $HOME/Dropbox/ -name stata.lic.$VERSION| tail -1)

if [[ -z $STATALIC ]]
then
	echo "Could not find Stata license"
	grep STATALIC $0
	exit 2
fi
docker run -it --rm \
  -v "${STATALIC}":/usr/local/stata/stata.lic \
  -v "$(pwd)":/project \
  -w /project \
  --entrypoint /bin/bash \
  $MYIMG $@

echo "-------------------------"
echo ""
echo "Replicator system"
echo "-----------------"
printf "%s " "*"
cat /etc/*release | grep PRETTY_NAME | awk -F= ' {print $2 } '
printf "%s " "*" $(cat /proc/cpuinfo | grep "model name" | awk -F: ' { sum+=1; model=$2 } END { print $2 ", " sum " cores" }') $(free -g | grep Mem | awk ' { print ", " $2 "GB memory" } ')
echo ""
printf "%s " "*" $(docker --version)
echo ""
printf "* %s version %d (Docker image %s)" $SOFTWARE $VERSION $MYIMG
echo ""



